---
# tasks file for mysql
- name: install python mysql bindings
  yum: name=python-mysqldb state=installed
  become: yes
  become_method: sudo

- name: Create MySQL Database
  mysql_db: name={{ wp_mysql_db}} state=present

- name: Create MySQL User
  mysql_user:
    name={{ wp_mysql_user }}
    password= {{ wp_mysql_password }}
    priv=*.*:ALL